using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems; //for mouse interactions

public class UIItemMerchant : MonoBehaviour {

    public ItemMerchant item;
    private Image spriteImage;
    //private UIItemMerchant selectedItem;
    //private Tooltip tooltip;

    private void Awake()
    {
        spriteImage = GetComponent<Image>();
        UpdateItem(null);
        //selectedItem = GameObject.Find("SelectedItem").GetComponent<UIItemMerchant>();
        //tooltip = GameObject.Find("Tooltip").GetComponent<Tooltip>();
    }

    public void UpdateItem(ItemMerchant item)
    {
        this.item = item;
        if(this.item != null)
        {
            spriteImage.color = Color.white;
            spriteImage.sprite = this.item.icon;
        }
        else
        {
            spriteImage.color = Color.clear;
        }
    }
/*

    //Mouse event generated by IPointerClickHandler interface
    public void OnPointerClick(PointerEventData eventData)
    {
        if(this.item != null) //If we are clicking on an item
        {

            if(selectedItem.item != null) //If we click on another item while selecting an item
            {
                ItemMerchant clone = new ItemMerchant(selectedItem.item);
                selectedItem.UpdateItem(this.item);
                UpdateItem(clone);
            }
            
            
            else //Click on an item while not selecting an item
            {
                selectedItem.UpdateItem(this.item);
                UpdateItem(null); 
            }
            
            
        
        
        }else if(selectedItem.item != null) //Drop an item into an empty slot
        {
            UpdateItem(selectedItem.item);
            selectedItem.UpdateItem(null);
        }
        
    }

    public void OnPointerEnter(PointerEventData eventData)
    {
        //generate tool tip for hovered item
        if(this.item != null)
        {
            //tooltip.GenerateTooltip(this.item);
        }
    }
   
    //Hide tooltip when no item is hovered
    public void OnPointerExit(PointerEventData eventData)
    {
        //tooltip.gameObject.SetActive(false);
        tooltip.HideTooltip();
    }
*/
}
